# Generated by Django 4.0.2 on 2022-04-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Location', models.CharField(max_length=50)),
                ('Crop_Id', models.CharField(max_length=50)),
                ('Crop_Type', models.CharField(max_length=50)),
                ('Crop_variaty', models.CharField(max_length=50)),
                ('Crop_name', models.CharField(max_length=50)),
                ('ExYielPHec', models.CharField(max_length=50)),
                ('Plant_hei', models.CharField(max_length=50)),
                ('CropPeriod', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tool_Id', models.CharField(max_length=50)),
                ('Tool_Name', models.CharField(max_length=50)),
                ('ToolRate', models.CharField(max_length=50)),
                ('Phone_no', models.CharField(max_length=50)),
            ],
        ),
    ]
